#!/bin/bash

# Reset ufw to default settings
ufw --force reset

# Set default policy to deny all incoming traffic
ufw default deny incoming

# Allow SSH connections
ufw allow 22

# Allow HTTP traffic
ufw allow 80

# Allow HTTPS traffic
ufw allow 443

# Enable ufw
ufw --force enable 